# Generated by Django 2.2.4 on 2019-09-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(default='', max_length=99),
        ),
    ]
