# Generated by Django 2.2.4 on 2019-08-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190827_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
