# Generated by Django 2.2.4 on 2019-09-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart_stock',
            field=models.IntegerField(default=0),
        ),
    ]
